version: '3'
services:
  web:
      build: ./
      ports:
          - "8080:80"
      volumes:
          - ./code:/code
      depends_on:
          - php
  php:
      image: php:7-fpm
      volumes:
          - ./code:/code
