version: '3'
services:
  web:
      build:
        context: .
        dockerfile: ./containers/nginx/Dockerfile
      ports:
          - "8080:80"
      # volumes:
      #     - ./code:/code
      depends_on:
          - php
  php:
      build:
        context: .
        dockerfile: ./containers/php/Dockerfile
      ports:
         - "9000:9000"
      # volumes:
      #     - ./code:/code
