version: '3'
services:
  web:
      build: ./containers/nginx
      ports:
          - "8080:80"
      volumes:
          - ./code:/code
      depends_on:
          - php
  php:
      build: ./containers/php
      volumes:
          - ./code:/code
