apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/run/php-fpm"
    #このパスはworkernode側のパスを指している
    #こことpod側で指定したコンテナのパスをvolumeで共通化させるようになる
    #pod側で指定したコンテナのパスとは今回でいうdeployment_laravel.ymlのmountPath: /var/run/php-fpm