apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nuxt
  name: nuxt
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nuxt
  type: NodePort
status:
  loadBalancer: {}
#docker-composeで定義したコンテナが8080:80になっているならば、nodePortServiceのportを8080、podのportを80にすれば良い
