apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: laravel
  name: laravel
spec:
  ports:
  - port: 23450
    protocol: TCP
    targetPort: 80
  selector:
    run: laravel
  type: NodePort
status:
  loadBalancer: {}